services:
  - type: web
    name: pontix-cloud-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: DEBUG
        value: "False"
      - key: REQUIRE_AUTH
        value: "True"
      - key: APP_URL
        scope: PROJECT_ID
        value: https://api-pontix-cloud.onrender.com
      - key: WEB_APP_URL
        scope: PROJECT_ID
        value: https://pontix-cloud.vercel.app
      - key: JWT_SECRET_KEY
        scope: PROJECT_ID
      - key: SUPABASE_URL
        scope: PROJECT_ID
      - key: SUPABASE_KEY
        scope: PROJECT_ID
      - key: SUPABASE_SERVICE_KEY
        scope: PROJECT_ID
      - key: RESEND_API_KEY
        scope: PROJECT_ID
      - key: RESEND_FROM_EMAIL
        value: noreply@pontix.com
      - key: CORS_ORIGINS
        value: https://pontix-cloud.vercel.app,https://localhost:3000,http://localhost:5173
      - key: LOG_LEVEL
        value: INFO
